### ISSUE TITLE
Environment variables are displayed as clear-text

### ISSUE THREAD

**Issue by rorpage** [appleboy/lambda-action#4]
When running this action the Lambda function environment variables are displayed clear-text in the build output. Is there a flag or option to suppress that output?

Thanks! Your code works like a charm otherwise!

**Comment by ptallen63** [comment]
Second @rorpage , Love the action....but can not use this anywhere if env vars are being logged.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@ptallen63 Do you have any screenshots?

**Comment by adriangodong** [comment]
Can verify this is happening. Here's an anonymized log from GHA:

```
##[command]/usr/bin/docker run --name e87b52daece746306b478d86dd660231940aa5_0747c0 ...
2020/03/31 05:22:05 {
  ...,
  Environment: {
    Variables: {
      AAA_BBB_CCC: "...",
      DDD_EEE_FFF: "..."
    }
  },
  FunctionArn: "arn:aws:lambda:us-east-1:...",
  FunctionName: "...",
  Handler: "...",
  ...
}
```

I'm not proficient in Go, but I believe this issue is caused by this line: https://github.com/appleboy/drone-lambda/blob/master/plugin.go#L137

Given that Actions log file for public repos are public and it is common to store runtime secrets in env var, I believe this is an urgent security issue.

**Comment by appleboy** [comment]
@adriangodong I will move the log message in debug mode.

**Comment by appleboy** [comment]
bump to v0.0.3 https://github.com/appleboy/lambda-action/releases/tag/v0.0.3

**Comment by adriangodong** [comment]
Confirmed 0.0.3 works! Thank you, much appreciated!
